[package]
name = "fsgc"
version = "0.4.1"
edition = "2018"


[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
clap = "3.0.0-beta.4"
glob = "0.3.0"
remove_dir_all = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
